<?xml version="1.0" encoding="utf-8"?><Database Name="zkkaMail" Class="zkkaMailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=62.116.202.237;Initial Catalog=zkkaMail;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zkkaMailConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ctTbl" Member="ctTbls">
    <Type Name="ctTbl">
      <Column Name="ChatNr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Navn" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Besked" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailBesked" Member="MailBeskeds">
    <Type Name="MailBesked">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fra" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Besked" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BrugerMail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>